### ISSUE TITLE
make all failed on Ubuntu (Linux)

### ISSUE THREAD

**Issue by SandyWare** [Isaac25silva/Driver-UM7#1]
Environment :  Linux Ubuntu 64 bit (16.04.1) , gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0
Issue : Make give below error during build.

[Makefile.zip](https://github.com/Isaac25silva/Driver-UM7/files/814016/Makefile.zip)

swae@ad:~/Downloads/Driver-UM7$ make all
Scanning dependencies of target comms
[ 16%] Building CXX object CMakeFiles/comms.dir/src/comms.o
/home/sware/Downloads/Driver-UM7/src/comms.cpp:53:27: fatal error: serial/serial.h: No such file or directory
compilation terminated.
CMakeFiles/comms.dir/build.make:62: recipe for target 'CMakeFiles/comms.dir/src/comms.o' failed
make[2]: *** [CMakeFiles/comms.dir/src/comms.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/comms.dir/all' failed
make[1]: *** [CMakeFiles/comms.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I am attaching makefile for your reference.

**Comment by Isaac25silva** [comment]
I fixed the error "fatal error: serial/serial.h: No such file or directory".
Now, you can try again.
Maybe you need install serial.h

**Comment by SandyWare** [comment]
Thanks lot for fix. I have clone latest code from git,
But now it gives below error :

CMakeFiles/imu.dir/src/imu.o: In function `main':
imu.cpp:(.text+0xda5): undefined reference to `serial::Serial::Serial(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, serial::Timeout, serial::bytesize_t, serial::parity_t, serial::stopbits_t, serial::flowcontrol_t)'
imu.cpp:(.text+0xde0): undefined reference to `serial::Serial::setPort(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
imu.cpp:(.text+0xdf7): undefined reference to `serial::Serial::setBaudrate(unsigned int)'
imu.cpp:(.text+0xe3a): undefined reference to `serial::Serial::setTimeout(serial::Timeout&)'
imu.cpp:(.text+0xe50): undefined reference to `serial::Serial::open()'
imu.cpp:(.text+0xe5f): undefined reference to `serial::Serial::isOpen() const'
imu.cpp:(.text+0x154f): undefined reference to `serial::Serial::~Serial()'
imu.cpp:(.text+0x15de): undefined reference to `serial::Serial::isOpen() const'
imu.cpp:(.text+0x15f1): undefined reference to `serial::Serial::close()'
imu.cpp:(.text+0x1633): undefined reference to `serial::Serial::~Serial()'
libcomms.so: undefined reference to `serial::Serial::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libcomms.so: undefined reference to `serial::Serial::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned long)'
libcomms.so: undefined reference to `serial::Serial::flushInput()'
libcomms.so: undefined reference to `serial::Serial::read(unsigned char*, unsigned long)'
libcomms.so: undefined reference to `serial::Serial::readline(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
libcomms.so: undefined reference to `serial::Serial::available()'
collect2: error: ld returned 1 exit status

**Comment by SandyWare** [comment]
thanks lot for all your suggestion. It's work now.

Edit CMakeLists.txt add you serial library path using link_directories.
     ex: link_directories(/home/xyz/Downloads/serial/devel/lib)
you can get serial library from below git path : 
    https://github.com/wjwwood/serial 

I hope this info may help someone in future :)
