### ISSUE TITLE
How to detect speed & Vehicle  movement

### ISSUE THREAD

**Issue by SandyWare** [Isaac25silva/Driver-UM7#2]
Driver-UM7 is a wonderfully library.
How can I get speed value & detect Vehicle turns (left, right, .... ) using Driver-UM7 library ?
you all suggestion & help is appreciated. thanks lots in advance.

**Comment by Isaac25silva** [comment]
You can get orientation values, only reading the value Euler_x, Euler_y and Euler_z. But you should configure if you want use magnetometer (magnetometer don't work with motors close), in the line 183, file imu.cpp
I use without magnetometer.

**Comment by SandyWare** [comment]
I am calculating velocity using below accelerometer velocity formula -
     Vt = V0 + a.t

I am got reference for below url :
  http://forum.arduino.cc/index.php?topic=289979.0

I am getting  IMU_ACCEL_X, IMU_ACCEL_Y, IMU_ACCEL_Z.
But I am failed to get register value of  DREG_ACCEL_RAW_TIME. 

I have added below lines class Registers:
class Registers {
     .............
     mag_bias(this, CREG_MAG_BIAS_X, 3),
     accelrometer_raw_time(this,DREG_ACCEL_TIME,3),
...................
const Accessor<uint32_t>  accelrometer_raw_time;


But it always print value as DREG_GYRO_RAW_TIME = 91.
So kindly help me getting  register DREG_ACCEL_RAW_TIME value ?

Help me if you have any better idea about calculating speed.

**Comment by SandyWare** [comment]
As you able to get DREG_GYRO_RAW_XY, DREG_ACCEL_RAW_XY value using your library.

On similar basis I need to get DREG_POSITION_NORTH, DREG_POSITION_EAST, DREG_GPS_SPEED, DREG_ACCEL_TIME, DREG_GYRO_TIME values. 

So what I am looking for is to register other "firmware_registers.h" to get its value 
Ex : DREG_POSITION_NORTH, DREG_POSITION_EAST, DREG_GPS_SPEED, DREG_ACCEL_TIME, DREG_GYRO_TIME. 

So kindly update how I can implements in using Class Registers & Accessor ?
So I can try out various math equation to get speed & turns ?
Your suggestion and help is highly appreciated.

**Comment by SandyWare** [comment]
It was my mistake 
 Here is code I changed to get value 
    void publishMsgs(um7::Registers& r)
  {  ......................
          IMU_ACCEL_TIME   = r.accelrometer_time.get(0);

Change in register construction 
    Registers() :
               accelrometer_time(this,DREG_ACCEL_PROC_TIME,3),

         add data member :     const Accessor<uint32_t>  accelrometer_time;


Print data in main 
      std::cout<<"ACCEL_TIME ="<<std::fixed<<IMU_ACCEL_TIME<<std::endl;

**What is difference between  get(0), get(1) & get(2) ?**
   ex:  IMU_ACCEL_TIME   = r.accelrometer_time.get(0);

I got time stamp value in format of :  ACCEL_TIME = 1163281280.000000
**How I can convert it into time stamp ?**
    ex: MM DD YYY : HH:mm:ss:ms.

**Comment by Isaac25silva** [comment]
I do not know, I never had to use these variables.
In this link: http://www.chrobotics.com/shop/um7-lt-orientation-sensor you can get the datasheet and know more about UM7.
Hope it help.
